### ISSUE TITLE
Allow collapsing user's rants and comments by default

### ISSUE THREAD

**Issue by lbfalvy** [joewilliams007/skyRant#8]
Devrant is a largely unified community, and it's great for that, but every now and then there comes some user whose style or topics I just really don't want to see in this context. If devrant was an actively moderated topical platform, this would not be an issue because the extremes could be avoided, but as it stands it's closer to a social platform, and an unmoderated one at that.

I don't think entirely erasing all information related to these users is a good idea, partly because the fact of missing information is important to avoid misunderstanding comment threads, partly because some indicator of the volume of content I'm ignoring is a useful metric of my understanding of the state of the community which can avoid sealing myself in a bubble.

My idea for a solution is a client-side list of usernames whose content is hidden by default and only metadata is shown. Tapping on this header can expand the content in case the user infers from context that it is relevant.

**Comment by lbfalvy** [comment]
I noticed that skyRant already supports blocking

**Comment by joewilliams007** [comment]
> I noticed that skyRant already supports blocking

Hi, thanks for the thought. At this point i blocked 9 people who post unrelated s... all the time. And to be honest this was a big reason why i started to make skyRant.

Thanks for the feedback anyhow!
